package Parsers;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.19 at 10:47:07 PM EEST 
//

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Gun }
     * 
     */
    public Gun createGun() {
        return new Gun();
    }

    /**
     * Create an instance of {@link Gun.Item }
     * 
     */
    public Gun.Item createGunItem() {
        return new Gun.Item();
    }

    /**
     * Create an instance of {@link Gun.Item.TTC }
     * 
     */
    public Gun.Item.TTC createGunItemTTC() {
        return new Gun.Item.TTC();
    }

}
